import { jsPDF } from "jspdf";
import { flattenForLayout, birdLabel, type PedigreeNode } from "./tree";

const GOLD = "#D4AF37";
const BLACK = "#000000";
const MUTED = "#666666";
const WHITE = "#FFFFFF";

/**
 * Draws a bird's pedigree as a vector fan chart (subject on the left,
 * ancestors fanning right by generation) and returns it as a Blob.
 * Runs entirely client-side, matching this app's existing pattern of doing
 * heavy processing in the browser (ffmpeg.wasm, tesseract.js) instead of a
 * server function.
 */
export function renderPedigreePdf(root: PedigreeNode, loftName?: string | null): Blob {
  const nodes = flattenForLayout(root);
  const maxGeneration = nodes.reduce((max, n) => Math.max(max, n.generation), 0);

  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const headerHeight = 70;
  const footerHeight = 34;
  const chartTop = headerHeight;
  const chartHeight = pageHeight - headerHeight - footerHeight;

  const colCount = maxGeneration + 1;
  const colWidth = pageWidth / colCount;
  const boxWidth = colWidth - 14;
  const boxHeight = 40;

  // Header
  doc.setFillColor(BLACK);
  doc.rect(0, 0, pageWidth, headerHeight, "F");
  doc.setTextColor(GOLD);
  doc.setFont("times", "italic");
  doc.setFontSize(20);
  doc.text(`Pedigree — ${birdLabel(root)}`, 24, 32);
  doc.setFontSize(10);
  doc.setTextColor(WHITE);
  doc.setFont("helvetica", "normal");
  doc.text(loftName ? `${loftName} · RollersOnly Pedigree Vault` : "RollersOnly Pedigree Vault", 24, 50);

  // Draw connector lines first (so boxes sit on top)
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.75);
  for (const { node, generation, slot } of nodes) {
    if (generation === maxGeneration) continue;
    const slotsInGen = 2 ** generation;
    const boxRightEdge = generation * colWidth + 7 + boxWidth;
    const childBoxLeftEdge = (generation + 1) * colWidth + 7;
    const y = chartTop + ((slot + 0.5) / slotsInGen) * chartHeight;

    const sireY = chartTop + ((slot * 2 + 0.5) / (slotsInGen * 2)) * chartHeight;
    doc.line(boxRightEdge, y, childBoxLeftEdge, sireY);

    const damY = chartTop + ((slot * 2 + 1.5) / (slotsInGen * 2)) * chartHeight;
    doc.line(boxRightEdge, y, childBoxLeftEdge, damY);
  }

  // Draw boxes
  for (const { node, generation, slot } of nodes) {
    const slotsInGen = 2 ** generation;
    const y = chartTop + ((slot + 0.5) / slotsInGen) * chartHeight - boxHeight / 2;
    const x = generation * colWidth + 7;

    doc.setDrawColor(GOLD);
    doc.setLineWidth(generation === 0 ? 1.5 : 0.75);
    doc.setFillColor(generation === 0 ? "#0A0A0A" : "#FAFAF8");
    doc.roundedRect(x, y, boxWidth, boxHeight, 3, 3, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(generation === 0 ? 11 : 9);
    doc.setTextColor(generation === 0 ? WHITE : BLACK);
    const name = node.name || "Unnamed";
    doc.text(truncate(doc, name, boxWidth - 10, generation === 0 ? 11 : 9), x + 6, y + boxHeight / 2 - 2);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(generation === 0 ? GOLD : MUTED);
    const sub = [node.ring_number, node.sex, node.color].filter(Boolean).join(" · ") || "—";
    doc.text(truncate(doc, sub, boxWidth - 10, 7.5), x + 6, y + boxHeight / 2 + 11);
  }

  // Empty-slot placeholders for missing ancestors within the requested depth
  for (const { node, generation, slot } of nodes) {
    if (generation === maxGeneration) continue;
    const slotsInGen = 2 ** generation;
    if (!node.sire) drawUnknownBox(doc, generation + 1, slot * 2, slotsInGen * 2, colWidth, boxWidth, boxHeight, chartTop, chartHeight);
    if (!node.dam) drawUnknownBox(doc, generation + 1, slot * 2 + 1, slotsInGen * 2, colWidth, boxWidth, boxHeight, chartTop, chartHeight);
  }

  // Footer
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.5);
  doc.line(24, pageHeight - footerHeight + 8, pageWidth - 24, pageHeight - footerHeight + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text(`Generated by RollersOnly · rollersonly.com/pedigree · ${new Date().toISOString().slice(0, 10)}`, 24, pageHeight - 14);

  return doc.output("blob");
}

function drawUnknownBox(
  doc: jsPDF,
  generation: number,
  slot: number,
  slotsInGen: number,
  colWidth: number,
  boxWidth: number,
  boxHeight: number,
  chartTop: number,
  chartHeight: number
) {
  const y = chartTop + ((slot + 0.5) / slotsInGen) * chartHeight - boxHeight / 2;
  const x = generation * colWidth + 7;
  doc.setDrawColor("#CCCCCC");
  doc.setLineWidth(0.5);
  doc.setFillColor("#F5F5F5");
  doc.roundedRect(x, y, boxWidth, boxHeight, 3, 3, "FD");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor("#AAAAAA");
  doc.text("Unrecorded", x + 6, y + boxHeight / 2 + 3);
}

function truncate(doc: jsPDF, text: string, maxWidth: number, fontSize: number): string {
  doc.setFontSize(fontSize);
  if (doc.getTextWidth(text) <= maxWidth) return text;
  let out = text;
  while (out.length > 1 && doc.getTextWidth(out + "…") > maxWidth) out = out.slice(0, -1);
  return out + "…";
}
